# Generated by Django 3.1 on 2020-08-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200807_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.OneToOneField(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.author'),
        ),
    ]
