# Generated by Django 3.1 on 2020-08-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200813_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
